version: "3.5"

services:
  nginx:
    image: jonasal/nginx-certbot:5.2.0-nginx1.26.0
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d

  nats-1:
    image: nats:2.10.16-alpine
    ports:
      - "4222:4222"
      - "7222:7222"
      - "7422:7422"
      - "1882:1883"
      - "8222:8222"
    volumes:
      - "./nats.conf:/etc/nats/nats-server.conf"
      - "./jetstream/nats-1:/nats/storage"
      - "./jwt/nats-1:/nats/jwt"
      - "nginx_secrets:/etc/nats/keys"
    environment:
      TZ: "Europe/Zurich"
      SERVER_NAME: "adhereup-broker-eu1"
      CLUSTER_USERNAME: ${CLUSTER_USERNAME}
      CLUSTER_PASSWORD: ${CLUSTER_PASSWORD}
      NATS_SYSTEM_ACCOUNT: ${NATS_SYSTEM_ACCOUNT}
      NATS_OPERATOR: ${NATS_OPERATOR}
      CERT_FILE: "/etc/nats/keys/live/nats.adhereup.com/fullchain.pem"
      KEY_FILE: "/etc/nats/keys/live/nats.adhereup.com/privkey.pem"
      ROUTES: "nats://${CLUSTER_USERNAME}:${CLUSTER_PASSWORD}@nats-2:6222\nnats://${CLUSTER_USERNAME}:${CLUSTER_PASSWORD}@nats-3:6222"
    command: "-c /etc/nats/nats-server.conf --http_port 8222"
    networks: ["nats"]
    depends_on: ["nginx"]

  nats-2:
    image: nats:2.10.16-alpine
    ports:
      - "4223:4222"
      - "7223:7222"
      - "7423:7422"
      - "1883:1883"
    volumes:
      - "./nats.conf:/etc/nats/nats-server.conf"
      - "nginx_secrets:/etc/nats/keys"
      - "./jetstream/nats-2:/nats/storage"
      - "./jwt/nats-2:/nats/jwt"
    environment:
      TZ: "Europe/Zurich"
      SERVER_NAME: "adhereup-broker-eu2"
      CLUSTER_USERNAME: ${CLUSTER_USERNAME}
      CLUSTER_PASSWORD: ${CLUSTER_PASSWORD}
      NATS_SYSTEM_ACCOUNT: ${NATS_SYSTEM_ACCOUNT}
      NATS_OPERATOR: ${NATS_OPERATOR}
      CERT_FILE: "/etc/nats/keys/live/nats.adhereup.com/fullchain.pem"
      KEY_FILE: "/etc/nats/keys/live/nats.adhereup.com/privkey.pem"
      ROUTES: "nats://${CLUSTER_USERNAME}:${CLUSTER_PASSWORD}@nats-1:6222\nnats://${CLUSTER_USERNAME}:${CLUSTER_PASSWORD}@nats-3:6222"
    command: "-c /etc/nats/nats-server.conf"
    networks: ["nats"]
    depends_on: ["nats-1", "nginx"]

  nats-3:
    image: nats:2.10.16-alpine
    ports:
      - "4224:4222"
      - "7224:7222"
      - "7424:7422"
      - "1884:1883"
    volumes:
      - "./nats.conf:/etc/nats/nats-server.conf"
      - "nginx_secrets:/etc/nats/keys"
      - "./jetstream/nats-3:/nats/storage"
      - "./jwt/nats-3:/nats/jwt"
    environment:
      TZ: "Europe/Zurich"
      SERVER_NAME: "adhereup-broker-eu3"
      CLUSTER_USERNAME: ${CLUSTER_USERNAME}
      CLUSTER_PASSWORD: ${CLUSTER_PASSWORD}
      NATS_SYSTEM_ACCOUNT: ${NATS_SYSTEM_ACCOUNT}
      NATS_OPERATOR: ${NATS_OPERATOR}
      CERT_FILE: "/etc/nats/keys/live/nats.adhereup.com/fullchain.pem"
      KEY_FILE: "/etc/nats/keys/live/nats.adhereup.com/privkey.pem"
      ROUTES: "nats://${CLUSTER_USERNAME}:${CLUSTER_PASSWORD}@nats-1:6222\nnats://${CLUSTER_USERNAME}:${CLUSTER_PASSWORD}@nats-2:6222"
    command: "-c /etc/nats/nats-server.conf"
    networks: ["nats"]
    depends_on: ["nats-1", "nginx"]

networks:
  nats:
    name: nats

volumes:
  nginx_secrets:
